version: '2'

services:
  jenkins:
    image: jenkins-master
    build: ./jenkins-master
    container_name: jenkins
    ports:
      - "8080:8080"
  slave:
    image: jenkins-slave
    build: ./jenkins-slave
    links:
      - jenkins:jenkins
